### ISSUE TITLE
Please fix Notifications

### ISSUE THREAD

**Issue by mediaexplorer74** [surya-sk/backlogs#4]
Hi! Very intersting software. Nice idea for making windows-phone great again ;)

At last src code comment your wrote:
"Notification don't work in this".

Do you have some plan to use push notifications? Some Google push notification service or another solution? =)

P.S. I noticed that your disabled Issues at Ambie-Mobile project. Why? Are you stopped it because of some problems to downgrade to os target 15063, yes? =) I solve this puzzle: https://github.com/mediaexplorer74/ambie
But... my "ambie remake" is too old... it's only alpha version... just for fun!

**Comment by surya-sk** [comment]
Thank you. 
I did have toast notifications in the previous version, but that was unreliable, so I got rid of it. I'm a bit busy at the moment so I haven't had time to look at alternatives, but I do plan to have push notifications, possible using MPNS but that seems to be unsupported. If you have any suggestions do let me know and please feel free to create a PR

**Comment by mediaexplorer74** [comment]
> Hi! Very intersting software. Nice idea for making windows-phone great again ;) WOW, I detected your application at MS Store! Cool ! ))))
> 
> At last src code comment your wrote: "Notification don't work in this".
> 
> Do you have some plan to use any push notifications? Some Google push notification service or another solution? =)
> 
> P.S. I noticed that your disabled Issues at Ambie-Mobile project. Why? Are you stopped it because of some problems to downgrade to os target 15063, yes? =) I solve this puzzle: https://github.com/mediaexplorer74/ambie But... my "ambie remake" is too old... it's only alpha version... just for fun!

**Comment by mediaexplorer74** [comment]
> Thank you. I did have toast notifications in the previous version, but that was unreliable, so I got rid of it. I'm a bit busy at the moment so I haven't had time to look at alternatives, but I do plan to have push notifications, possible using MPNS but that seems to be unsupported. If you have any suggestions do let me know and please feel free to create a PR

OK. Thank you very much for fast reply. You are great C# Developer. Nice to meet you.

Cheers up

Best,

mediaexplorer74

**Comment by surya-sk** [comment]
And as for Ambie, yes. I was getting too many errors so I didn't really spend too much time on it. Glad you got it to work though, I'll have a look

**Comment by surya-sk** [comment]
Notifications are now working again in version 0.9.4, which should be in the Store soon.

**Comment by mediaexplorer74** [comment]
> Notifications are now working again in version 0.9.4, which should be in the Store soon.

Great job! :)
Ohhh.... I noticed that you deleted Uno branch from your Backlogs project. :( Why? Is Uno more difficult that XF (Xamarin Forms)?  I hope once upon the time you'll return to idea of some multi-platform edition of Movie/Game Backlogs super-app... ^ ^

**Comment by surya-sk** [comment]
Many things are broken or missing from UWP and it got annoying at one point. So instead I just made a web app in Blazor: https://backlogs.azurewebsites.net/

**Comment by mediaexplorer74** [comment]
Wow, I see that Backlogs' mvvm branch has fresh updates. 
I feel that you reilized tooo many crazy new features! :)  Very interesing =) I started to download your fresh Backlogs repo =)
MVVM is so cool thing =) 
You're great developer!
Cheers up,
mediaexplorer74

**Comment by surya-sk** [comment]
Thanks so much! I wanted to learn MVVM and also having reusable ViewModels means I can easily rewrite just the UI for Uno platform in the future, so I decided to do a little rewrite.

**Comment by mediaexplorer74** [comment]
> I wanted to learn MVVM and also having reusable ViewModels means I can easily rewrite just the UI for Uno platform in the future, so I decided to do a little rewrite.

Very cool! :)
I dream that you'll unerase (return) your "Uno" branch for great Backlogs Uno edition creation! :) 
And (Just for Uno branch) Readme.md needed where to note the required os. builds (Windows, Android, MacOs, etc.) ;)
Cheers up,
mediaexplorer74

**Comment by mediaexplorer74** [comment]
Wow, MVVM branch returned :) ANd... 500 commits! Congradulations 💯 💯 💯 💯 💯
