### ISSUE TITLE
ComboBoxes and TimePicker are crashing the app when changed after moving to MVVM

### ISSUE THREAD

**Issue by surya-sk** [surya-sk/backlogs#7]
**Describe the bug**
ComboBoxes and TimePicker are crashing the app when changed after moving to MVVM. Happens on nearly all pages with no exception or Stack Trace. Need to somehow debug and fix this.

**To Reproduce**
1. Click on any ComboBox
2. Choose an option
3. App will crash even with debugger attached 

**Expected behavior**
The changes should be registered and more importantly, not crash the app

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**
 - Device: Microsoft Lumia 950
 - OS: Windows 10 Mobile

**Additional context**
Maybe moving from x:Bind to Binding will fix the issue?

**Comment by surya-sk** [comment]
This is caused when the OnChanged event is triggered even if there hasn't been any change. Fixes in 967411dbc2b5e7b219da5fd7297cbe1c6ba96ea7 and 71e08a2d34104c68b3bc891d2b31e1f5d3b1664b

**Comment by mediaexplorer74** [comment]
> Maybe moving from x:Bind to Binding will fix the issue?

Idk =)

> surya-sk closed this as _completed_

Congradulations :)
Wow, you continued the Backlogs dev :) Perfect!

**Comment by surya-sk** [comment]
Yep, that fixes it too. I decided to go with this one because of consistency, because I'm using x:Bind everywhere. I'm not sure which one is technically better though

**Comment by mediaexplorer74** [comment]
> * Device: Microsoft Lumia 950

Wow, You also have Lumia 950.  So I. 👍  
I noticed that your deleted _mvvm_ branch. Only _master_ and _dev_ branches stayed at now. Ok!
I hope you transferred your mvvm's completed tasks onto dev...   
Still hope that you'll plan to reanimate your **uno** branch :)

**Comment by surya-sk** [comment]
Yep, the 950 is a great device indeed.
 I did merge the mvvm branch to dev and eventually to master :)
My next goals are to first improve performance, and then use those ViewModels for Uno
